default_connection_name = "advanced_data_engineering_snowflake"

[connections.advanced_data_engineering_snowflake]
account = "yWIGNUGR-MFB24900"
user = "nrashinkar"
password = "Snowflakein2025$$"
warehouse = "COMPUTE_WH"
role = "ACCOUNTADMIN"
